export const TREE_UI = {
  cellPx: 72,
  core: { gx: 2, gy: 2, radiusPx: 26 }, // Absolute grid cell of the black hole core and its disc radius.
  nodePx: 44,
  keystonePx: 58,
  lockPx: 40,
  zoomMin: 0.5,
  zoomMax: 2,
  zoomWheelFactor: 1.1,
  edges: {
    mainWidth: 3,
    latticeWidth: 2,
    // Opacity ladder: purchased-to-purchased brightest, frontier next, fully locked dimmest but still clearly connected.
    mainLit: 1,
    mainFrontier: 0.85,
    mainDim: 0.6,
    latticeLit: 0.8,
    latticeDim: 0.5,
  },
  iconGlyphs: {
    size: '◎',
    tick: '⟳',
    damage: '✸',
    crit: '⊕',
    critDamage: '❈',
    time: '⧗',
    static: '⚡',
    chain: '⛓',
    chainDamage: '↯',
    chainCrit: '⊗',
    chainCritDamage: '❖',
    timeOnKill: '⏲',
    fork: '⑂',
    range: '⇢',
    planet: '◍',
    star: '★',
    golden: '◆',
    radioactive: '☢',
    comet: '☄',
    laser: '⌁',
    orb: '◔',
    moon: '☾',
    density: '✱',
    field: '❋',
    crowd: '⁂',
    pull: '↺',
    respawn: '♻',
  } as Record<string, string>,
} as const;
