export const VISUAL = {
  backgroundColor: 0x05030f,
  // Per-second easing rate for the camera view/horizon scale toward its growth-stage target - higher = snappier, lower = floatier. Prevents the zoom from jumping when a growth stage flips.
  cameraZoomSmoothingPerSecond: 3.5,
  starfield: {
    starCount: 220,
    minRadius: 0.4,
    maxRadius: 1.6,
    minAlpha: 0.15,
    maxAlpha: 0.7,
    color: 0xffffff,
    lensing: {
      zoneScale: 3.2,
      deflectionStrength: 0.35,
      maxArcRadians: 0.9,
      hideBelowScale: 1.05,
      streakColor: 0xffe2c2,
      rotationRadiansPerSecond: 0.02,
      halo: { count: 90, minAlpha: 0.04, maxAlpha: 0.28 },
    },
  },
  blackHole: {
    voidColor: 0x000000,
    accretion: {
      color: 0xffb26b,
      arcCount: 3,
      arcSpanRadians: 1.9,
      radiusScale: 1.18,
      width: 2,
      alpha: 0.4,
      spinRadiansPerSecond: 0.35,
    },
    photonRing: {
      textureSizePx: 512,
      textureRadiusFraction: 0.625,
      ringScale: 1.05,
      baseAlpha: 0.95,
      shimmerAlpha: 0.07,
      shimmerHz: 0.35,
      scalePulse: 0.012,
      doppler: { alpha: 0.8, spinRadiansPerSecond: 0.12 },
    },
  },
  breakerRing: {
    color: 0x22d3ee,
    width: 2,
    alpha: 0.8,
    telegraph: { width: 4, color: 0x67e8f9, alpha: 0.95 },
  },
  healthBar: {
    widthScale: 1.6,
    heightPx: 3,
    offsetScale: 1.35,
    backgroundColor: 0x1e293b,
    backgroundAlpha: 0.8,
    fillColor: 0x34d399,
    fillAlpha: 0.95,
  },
  hitFlash: { durationSeconds: 0.08 },
  crackStages: [0.75, 0.5, 0.25],
  spaghettification: {
    zoneWorldUnits: 90,
    maxStretch: 1.9,
    minScale: 0.01,
    scaleExponent: 0.7,
  },
  textures: { baseSizePx: 96, variantsPerTier: 12 },
  particles: {
    poolSize: 512,
    pullStrength: 14000,
    minPullDistance: 50,
    dragPerSecond: 1.4,
    tangentialFactor: 0.55,
    textureSizePx: 16,
  },
  lightning: {
    boltColor: 0x7dd3fc,
    boltWidthPx: 2,
    boltLifeSeconds: 0.3,
    segmentsMin: 6,
    segmentsMax: 10,
    jitterWorldUnits: 14,
    poolSize: 32,
    ring: {
      color: 0x60a5fa,
      segments: 12,
      spikeWorldUnits: 4,
      widthPx: 1.5,
      alphaBase: 0.6,
      alphaPulse: 0.3,
      pulseHz: 1.6,
      jitterHz: 8,
    },
  },
  golden: {
    ringColor: 0xffd700,
    ringWidthPx: 2,
    ringExtraWorldUnits: 3,
    glowColor: 0xffe066,
    glowAlpha: 0.16,
    glowRadiusMult: 1.5,
    alphaBase: 0.75,
    alphaPulse: 0.25,
    pulseHz: 1.2,
  },
  radioactive: {
    ringColor: 0x84cc16,
    ringWidthPx: 2,
    ringExtraWorldUnits: 3,
    glowColor: 0xa3e635,
    glowAlpha: 0.16,
    glowRadiusMult: 1.5,
    alphaBase: 0.75,
    alphaPulse: 0.25,
    pulseHz: 1.2,
  },
  radioactiveFallout: {
    color: 0x65a30d,
    alpha: 0.22,
  },
  moon: {
    ringColor: 0xcbd5e1,
    ringWidthPx: 2,
    ringExtraWorldUnits: 3,
    glowColor: 0xe2e8f0,
    glowAlpha: 0.16,
    glowRadiusMult: 1.5,
    alphaBase: 0.75,
    alphaPulse: 0.25,
    pulseHz: 1.2,
  },
  satellite: {
    color: 0xd8dee9,
    radiusPx: 4,
    glowColor: 0xf1f5f9,
    glowAlpha: 0.35,
    glowRadiusMult: 2.2,
  },
  orb: {
    color: 0xf5f3ff,
    glowColor: 0xa855f7,
    radiusPx: 5,
    glowRadiusMult: 2.4,
    glowAlpha: 0.45,
    alphaBase: 0.85,
    alphaPulse: 0.15,
    pulseHz: 3,
  },
  comet: {
    tail: {
      segments: 7,
      lengthRadiusMult: 7,
      startRadiusMult: 0.9,
      endRadiusMult: 0.15,
      startAlpha: 0.5,
      color: 0xfb923c,
      innerColor: 0xffe4c4,
      innerAlpha: 0.35,
      innerRadiusMult: 0.45,
    },
    glowColor: 0xffd7a8,
    glowAlpha: 0.4,
    glowRadiusMult: 2.4,
    alphaBase: 0.75,
    alphaPulse: 0.25,
    pulseHz: 2.2,
  },
  supernova: {
    ringColor: 0xfff4c1,
    ringWidthPx: 5,
    ringAlpha: 0.9,
    glowColor: 0xffe9a8,
    glowAlpha: 0.4,
  },
  laser: {
    coreColor: 0xfff4e6,
    coreAlpha: 0.95,
    coreWidthPx: 2,
    glowColor: 0xff4d2e,
    glowAlpha: 0.3,
    glowWidthPx: 6,
    blastReachWorldUnits: 4000,
    mountGlowColor: 0xff9d3d,
    mountGlowAlpha: 0.3,
    mountGlowRadiusWorldUnits: 30,
  },
  depths: {
    starfield: -10,
    blackHole: -5,
    blackHoleVoid: -4,
    cometTail: -1,
    celestials: 0,
    cracks: 1,
    particles: 2,
    shading: 3,
    lightning: 3,
    goldenGlow: 3,
    radioactiveGlow: 3,
    radioactiveFallout: 3,
    supernova: 3,
    moonGlow: 3,
    laser: 3,
    satellites: 4,
    orbs: 4,
    healthBars: 4,
    breakerRing: 5,
    floatingText: 6,
  },
} as const;
